# Copyright 2026 Atakku <https://atakku.dev>
#
# This project is dual licensed under MIT and Apache.

# Gradle setup
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true

# Mod properties
mod_id=hrt_worldgen
mod_name=hrt-worldgen
mod_group=zone.hrt
mod_version=1.1.0

minecraft_version=1.21.1
mappings_version=2024.11.17
neo_version=21.1.250

# Dependencies
lombok_version=1.18.32
